### ISSUE TITLE
Is it possible to select the range of indexes?

### ISSUE THREAD

**Issue by AngeloMetal** [PawelGorny/lostword#2]
Hi again, I'd like to know if there is an option for brute forcing many derivation paths (indexes specifically) at once. For example I want to brute force the addresses below, but I can't with my hand. (I want to leave it all night long)

```
m/84'/0'/0'/1/0
m/84'/0'/0'/1/1
m/84'/0'/0'/1/2
m/84'/0'/0'/1/3
...
m/84'/0'/0'/1/99
m/84'/0'/0'/1/100
```
Your program has made my life easier btw.

**Comment by PawelGorny** [comment]
Done! Check version 0.10, updated readme and examples 5, 17.
