### ISSUE TITLE
Time Estimation for permutation check case

### ISSUE THREAD

**Issue by JZ6** [PawelGorny/lostword#4]
Is there a rough estimation on how long it will take to check 12! cases of a permutation check on a 16 core cpu?

Would you say it’s at least 1000 checks per second per core?

**Comment by PawelGorny** [comment]
I may add counter (number of operations per minute, per second), but:
which worker you talk about? Because you ask about 12! I guess you have 12 words and you do not know order, so you want to use "permutation check", right?

**Comment by JZ6** [comment]
Yes exactly, i am currently running permutation and trying to estimate a worst case time. 

Operations per minute may be too much overhead, a simple counter that prints say every 100 thousand operations should suffice
